language: r

r:
  - release

sudo: required
dist: bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
