language: r

r:
  - release

sudo: required
dist: bionic

addons:
  apt:
    packages:
      - libnetcdf-dev
      - netcdf-bin

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
grep -q -R -e "WARNING" -e "ERROR" "${RCHECK_DIR}/00check.log"; RETVAL=$?
